### ISSUE TITLE
Some situation leads to 100% cpu on dev machine

### ISSUE THREAD

**Issue by mcpherrinm** [square/keywhiz-fs#13]
I've had something happen two or three times recently where I've had a keywhiz process using > 100% cpu on my mac.  I'm not sure what it is -- but both times it happened when i'd closed the terminal I was running it in.  I'll attempt a proper repro & profile.

**Comment by alokmenghrajani** [comment]
I ran into this issue tonight. Trying to get to the bottom of it.

**Comment by alokmenghrajani** [comment]
I believe our memory leaks are now fixed. I'm unsure about the CPU stuff, we can re-open this issue if it shows up again.

**Comment by mcpherrinm** [comment]
Definitely still present.  Attached with dtruss:  It wasn't making any system calls.  I've attached a sample taken before I had to kill -9 it.
[Sample of keywhizfs.txt](https://github.com/square/keywhiz-fs/files/147914/Sample.of.main4.txt)

**Comment by csstaub** [comment]
@mcpherrinm would be nice to have a goroutine dump

**Comment by mcpherrinm** [comment]
Yeah, it really would be, but the process was sufficiently wedged that I'm not sure how to get one of them.  Let's talk about this today.

**Comment by mcpherrinm** [comment]
I had this happen again.  I'm fairly confident at this point it's an OS X issue:  I do much more dev work on Linux, where I haven't had it happen.

I tried to get a goroutine dump with "delve", but the debugger crashed.

**Comment by mcpherrinm** [comment]
It happened again.  Delve didn't crash this time, but did print an error and then kwfs exited.  Sorry,  I didn't get the error.  The golang debugger situation is very frustrating.

It starts when I ctrl-c the binary.
